version: "3"
services:
  monitor:
    build: monitor
    network_mode: host
  controller:
    build: controller
    network_mode: host
    volumes:
      - config:/etc/autoshut
    depends_on:
      - monitor

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind
